-- ============================================================
-- Recriação das tabelas do app-gestao-os (ordens_servico e tecnico_padrao)
-- Reconstruído a partir do uso real no código (js/app.js, js/utils.js),
-- já que o schema nunca foi versionado em SQL.
-- Rode este script no Supabase Dashboard > SQL Editor.
-- ============================================================

-- ========== TABELA: ordens_servico ==========
create table if not exists public.ordens_servico (
  id bigint generated by default as identity primary key,
  numero_os text not null,
  data_abertura date not null,
  cliente text not null,
  telefone text,
  endereco text,
  complemento text,
  cep text,
  aparelho text not null,
  marca text,
  valor_servico numeric(10, 2) not null default 0,
  valor_pecas numeric(10, 2) not null default 0,
  periodo_visita text,
  campanha text,
  status text not null default 'Visita',
  observacoes text,
  created_at timestamptz not null default now()
);

-- ========== TABELA: tecnico_padrao ==========
create table if not exists public.tecnico_padrao (
  id bigint generated by default as identity primary key,
  nome_tecnico text,
  telefone_tecnico text,
  eh_padrao boolean not null default false,
  created_at timestamptz not null default now()
);

-- ========== RLS (Row Level Security) ==========
-- O app usa login anônimo (supabase.auth.signInAnonymously()), então as
-- políticas liberam acesso total para qualquer usuário autenticado
-- (inclusive sessões anônimas), sem distinção de dono do registro.

alter table public.ordens_servico enable row level security;
alter table public.tecnico_padrao enable row level security;

create policy "ordens_servico_acesso_autenticado"
  on public.ordens_servico
  for all
  to authenticated
  using (true)
  with check (true);

create policy "tecnico_padrao_acesso_autenticado"
  on public.tecnico_padrao
  for all
  to authenticated
  using (true)
  with check (true);

-- ============================================================
-- IMPORTANTE: além de rodar este script, confirme que o login anônimo
-- está habilitado em Authentication > Providers > Anonymous Sign-Ins.
-- Sem isso, supabase.auth.signInAnonymously() falha e nada funciona,
-- mesmo com o schema e as policies corretos.
-- ============================================================
